name: Python Lint & Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@latest

      - name: Set up Python
        uses: actions/setup-python@latest
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyright black
          pip install deploy/requirements.txt

      - name: Run Pyright lint
        run: |
          npx pyright --level warning && black * --line-length 120
